# Generated by Django 5.1.4 on 2025-01-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "userstuff",
            "0002_remove_userprofile_user_address_cartproduct_myorder_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("imgUrl", models.URLField()),
                ("imgUrl2", models.URLField(blank=True, null=True)),
                ("short_desc", models.TextField()),
                ("net", models.CharField(max_length=100)),
                ("tags", models.CharField(blank=True, max_length=255, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("qty", models.CharField(blank=True, max_length=50, null=True)),
                ("category_id", models.CharField(max_length=255)),
                ("sub_cate", models.CharField(max_length=255)),
                ("desc", models.TextField()),
                ("isAvailable", models.BooleanField(default=True)),
            ],
        ),
    ]
