# Generated by Django 5.1.4 on 2025-01-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userstuff", "0003_fooditem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=100)),
                ("imgSrc", models.URLField()),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
