# Generated by Django 5.1.4 on 2025-01-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userstuff", "0004_productcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="food_id",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
