# Generated by Django 5.1.4 on 2025-01-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userstuff", "0005_fooditem_food_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproduct",
            name="category_id",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="desc",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="food_id",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="imgUrl2",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="isAvailable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="sub_cate",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="tags",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="imgUrl",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="net",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="qty",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="short_desc",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
