# Generated by Django 5.1.4 on 2025-01-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userstuff", "0006_cartproduct_category_id_cartproduct_desc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartproduct",
            name="category_id",
        ),
        migrations.RemoveField(
            model_name="cartproduct",
            name="desc",
        ),
        migrations.RemoveField(
            model_name="cartproduct",
            name="food_id",
        ),
        migrations.RemoveField(
            model_name="cartproduct",
            name="imgUrl2",
        ),
        migrations.RemoveField(
            model_name="cartproduct",
            name="isAvailable",
        ),
        migrations.RemoveField(
            model_name="cartproduct",
            name="sub_cate",
        ),
        migrations.RemoveField(
            model_name="cartproduct",
            name="tags",
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="imgUrl",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="net",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="qty",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="short_desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
