# Generated by Django 5.1.4 on 2025-01-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userstuff", "0007_remove_cartproduct_category_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartproduct",
            name="user",
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
