# Generated by Django 5.1.4 on 2025-01-19 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userstuff", "0008_remove_cartproduct_user_cartproduct_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartproduct",
            name="token",
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
