# Generated by Django 5.1.4 on 2025-01-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userstuff", "0009_remove_cartproduct_token_cartproduct_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="qty",
            field=models.CharField(max_length=20),
        ),
    ]
