# Generated by Django 5.1.4 on 2025-01-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userstuff", "0011_myorder_payment_id_alter_myorder_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="myorder",
            name="address_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
