# Generated by Django 5.1.4 on 2025-01-20 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userstuff", "0012_myorder_address_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myorder",
            name="address_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="userstuff.address",
            ),
        ),
    ]
