# Generated by Django 5.1.4 on 2025-01-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userstuff", "0013_alter_myorder_address_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="qty",
            field=models.IntegerField(),
        ),
    ]
