# Generated by Django 5.1.4 on 2025-02-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userstuff", "0014_alter_cartproduct_qty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="imgSrc",
            field=models.ImageField(upload_to="product_category/"),
        ),
    ]
