# Generated by Django 5.1.4 on 2025-02-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userstuff", "0015_alter_productcategory_imgsrc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="imgSrc",
            field=models.URLField(),
        ),
    ]
