# Generated by Django 5.1.4 on 2025-02-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userstuff", "0016_alter_productcategory_imgsrc"),
    ]

    operations = [
        migrations.AddField(
            model_name="myorder",
            name="is_delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="myorder",
            name="otp_token",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
