# Generated by Django 5.1.4 on 2025-02-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userstuff", "0017_myorder_is_delivered_myorder_otp_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myorder",
            name="otp_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
