# Generated by Django 5.1.4 on 2025-02-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userstuff", "0018_alter_myorder_otp_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myorder",
            name="otp_token",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
