# Generated by Django 5.1.4 on 2025-01-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("nic", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("contact_number", models.CharField(max_length=15)),
                ("gender", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("address", models.TextField()),
                ("job_role", models.CharField(max_length=100)),
                ("qualifications", models.TextField()),
            ],
        ),
    ]
