# Generated by Django 5.1.4 on 2025-01-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="contact_number",
            new_name="contactNumber",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="job_role",
            new_name="jobrole",
        ),
    ]
