# Generated by Django 5.1.4 on 2025-02-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_employeeattendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="aadhaarImage",
            field=models.ImageField(default=1, upload_to="docs/"),
            preserve_default=False,
        ),
    ]
