# Generated by Django 5.1.4 on 2025-02-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_inventoryitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact", models.CharField(max_length=255)),
                ("specialty", models.CharField(max_length=255)),
                ("rating", models.IntegerField(default=3)),
                ("last_delivery", models.DateField()),
            ],
        ),
    ]
