# Generated by Django 5.1.4 on 2025-02-06 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="last_delivery",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="ConsumptionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_consumed", models.FloatField()),
                ("consumed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.inventoryitem",
                    ),
                ),
            ],
        ),
    ]
